#!/bin/sh
# Strip Cursor co-author trailers before commit message checks.

msg_file="$1"
[ -f "$msg_file" ] || exit 0

tmp="${msg_file}.clean"
grep -viE '^[Cc]o-[Aa]uthored-[Bb]y:.*([Cc]ursor|cursoragent@cursor\.com)' "$msg_file" > "$tmp"
mv "$tmp" "$msg_file"
exit 0
